stages:
    - lint
    - test
    - build
    - push

lint:
  image: golang:alpine
  stage: lint
  before_script:
    - apk add --no-cache make
    - go install golang.org/x/lint/golint
  script:
    - make lint

test:
  image: golang:alpine
  stage: test
  before_script:
    - apk add --no-cache make
  script:
    - make test

build:
  services:
    - docker:dind
  stage: build
  image: docker:latest
  needs:
    - lint
    - test
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/ 
  script:
    - docker build -t app:$CI_COMMIT_TAG .
    - docker tag app:$CI_COMMIT_TAG app:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}

push:
  image: docker:latest
  services:
    - docker:dind
  stage: push
  needs: [build]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push app:$CI_COMMIT_TAG
    - docker push app:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}