stages:
    - lint
    - test

lint:
  image: golang:alpine
  stage: lint
  script:
    - apk add --no-cache make
    - go install golang.org/x/lint/golint
    - make lint

test:
  image: golang:alpine
  stage: test
  script:
      - apk add --no-cache make
      - make test