name: Go

on: pull_request

env:
  REGISTRY: cr.yandex
  IMAGE_NAME: ${{ github.repository }}

jobs:

  lint:
    runs-on: yandex-runner
    steps:
    - name: checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Install golint
      run: go install golang.org/x/lint/golint

    - name: Lint
      id: lint
      run: make lint

  test:
    runs-on: yandex-runner
    steps:
    - name: checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Test
      run: make test
